version: "2.4"

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  ssoready-auth:
    image: ssoready/ssoready-auth:sha-18090f8
    environment:
      AUTH_SERVE_ADDR: ":80"
      AUTH_DB: "postgres://postgres:password@postgres/postgres"
      AUTH_BASE_URL: "http://localhost:8080"
      AUTH_DEFAULT_ADMIN_TEST_MODE_URL: "http://localhost:8083/test-mode"
      AUTH_SAML_STATE_SIGNING_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
    ports:
      - "8080:80"

  flask-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - SSOREADY_API_KEY=${SSOREADY_API_KEY}
      - SSOREADY_ORGANIZATION_ID=${SSOREADY_ORGANIZATION_ID}
    depends_on:
      - ssoready-auth

  ssoready-api:
    image: ssoready/ssoready-api:sha-18090f8
    environment:
      API_SERVE_ADDR: ":80"
      API_DB: "postgres://postgres:password@postgres/postgres"
      API_DEFAULT_AUTH_URL: "http://localhost:8080"
      API_DEFAULT_ADMIN_SETUP_URL: "http://localhost:8083/setup"
      API_GOOGLE_OAUTH_CLIENT_ID: "171906208332-m8dg2p6av2f0aa7lliaj6oo0grct57p1.apps.googleusercontent.com"
      API_SAML_STATE_SIGNING_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
    ports:
      - "8081:80"

  ssoready-app:
    image: ssoready/ssoready-app:sha-18090f8
    environment:
      APP_SERVE_PORT: "80"
      APP_APP_URL: "http://localhost:8082"
      APP_PUBLIC_API_URL: "http://localhost:8081"
      APP_API_URL: "http://localhost:8081/internal/connect"
      APP_GOOGLE_OAUTH_CLIENT_ID: "171906208332-m8dg2p6av2f0aa7lliaj6oo0grct57p1.apps.googleusercontent.com"
    ports:
      - "8082:80"

  # Optional. If you don't need the self-serve setup UI for configuring SAML and
  # SCIM, you can skip ssoready-admin.
  ssoready-admin:
    image: ssoready/ssoready-admin:sha-18090f8
    environment:
      ADMIN_SERVE_PORT: "80"
      ADMIN_API_URL: "http://localhost:8081/internal/connect"
    ports:
      - "8083:80"